### ISSUE TITLE
Backend menu group not highlighted

### ISSUE THREAD

**Issue by jurajkapsz** [DeuxHuitHuit/cache_management#6]
When the Cache Management `admin page` is shown, the `System` menu is not highlighted like it is for other pages under System menu.

I did not figure this one out.

**Comment by nitriques** [comment]
Well, me neither !!! (It must have to do with the url not actually being in system...)

But it could be easy to do via javascript...

**Comment by nitriques** [comment]
This is why ... https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.administrationpage.php#L1178-L1195

**Comment by nitriques** [comment]
BUT, Thank God Symphony has something for us! https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.administrationpage.php#L790

**Comment by jurajkapsz** [comment]
Magic for me.

I've tried to take a look on Tracker extension how its made there, but did not get to the difference.

But it works now, thanks :)

**Comment by nitriques** [comment]
@jurajkapsz I've release 1.3.1 with a bugfix... let's see how your changes to the meta.xml file will do!

Thanks again!

**Comment by jurajkapsz** [comment]
Cool, let's see :)
