### ISSUE TITLE
Bug with Symphony "Manager" User Type - not showing up in System Nav Menu

### ISSUE THREAD

**Issue by bzerangue** [DeuxHuitHuit/cache_management#8]
@nitriques - I am running into the problem with the Cache Management extension where the Symphony "Manager" user type does not have the Cache Management menu option under the System Nav Menu. If I am under the "Developer" user type, Cache Management menu option is available to me in the System Nav Menu. 

I am running Symphony 2.3.3 and Cache Management 1.3.1.

**Comment by nitriques** [comment]
Ok first of all:

Can you add `var_dump($author, $author->);die;` on that line please ?

It should work on 2.3.3 as per this https://github.com/symphonycms/symphony-2/blob/2.3.3/symphony/lib/toolkit/class.administrationpage.php#L479-L489

If values are good, then it's an old Symphony bug....

**Comment by nitriques** [comment]
This is not reproducible with both latest version, so closing.
